name: dl-project
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - pytorch-cuda=12.1  # adjust to match your CUDA version
  - pip:
      - numpy
      - pandas
      - matplotlib
      - pillow
      - pyyaml
      - tensorboard
      - wandb
      - kaggle
      - ipykernel
